language: c
os: linux
dist: trusty
sudo: required
install:
  - wget -qO - https://packages.irods.org/irods-signing-key.asc | sudo apt-key add -
  - echo "deb [arch=amd64] https://packages.irods.org/apt/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/renci-irods.list
  - sudo apt-get update -q
  - sudo apt-get install -y -q fuse libfuse-dev irods-dev irods-runtime irods-externals-cmake3.5.2 irods-externals-clang3.8-0 irods-externals-cppzmq4.1-0 irods-externals-libarchive3.1.2-0 irods-externals-avro1.7.7-0 irods-externals-boost1.60.0-0 irods-externals-clang-runtime3.8-0 irods-externals-jansson2.7-0 irods-externals-zeromq4-14.1.3-0 irods-icommands
  - export LD_LIBRARY_PATH=/opt/irods-externals/clang-runtime3.8-0/lib/
  - export PATH=/opt/irods-externals/cmake3.5.2-0/bin:$PATH
script:
  - cmake .
